### ISSUE TITLE
Реализовать роутинг на клиенте

### ISSUE THREAD

**Issue by WIVSW** [hikkah-squad/chitchat#14]
Может быть выполнена, только после #12

# Проблема
Сейчас в чате нет компонентов отвечающих за страницы сайта и возможности переключаться между страницами. Нужно реализовать маршрутизацию.

# Ожидаемый результат
1. Нужно прикрутить `Browser Router`, как [например тут](https://github.com/WIVSW/dashboard-spa/blob/develop/src/ui/router.jsx), но без проверки на авторизованность, т.к. она еще не реализована.
2. в папке `chitchat/src/pages` должны лежать реакт компоненты, которые отвечают за определенную страницу и содержать только какой-то временный текст, чтобы можно было проверить маршрутизацию (роутинг), например: `This is a login page`.
3. Все эти страницы должны быть подключены к роутеру по таким маршрутам:
- `'/login/'` - страница авторизации
- `'/'` - главная страница
- `'/profile/:id'` - страница информации о пользователе, где его можно будет добавить в контакты и если юзер смотрит на свой профиль, то отредактировать.
- `'/room/:id'` - страница где идет переписка
- `'/settings/'` - страница пользовательских настроек (включить/выключить десктоп нотификации)
- Страница для ошибки 404 если ни одна страница не была выбрана.

**Comment by Ba-stian** [comment]
Что из себя должна представлять 404?

**Comment by yukonovalov** [comment]
> Что из себя должна представлять 404?

https://ru.wikipedia.org/wiki/%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0_404

**Comment by WIVSW** [comment]
> Что из себя должна представлять 404?

в папке chitchat/src/pages должны лежать реакт компоненты, которые отвечают за определенную страницу и содержать только какой-то временный текст, чтобы можно было проверить маршрутизацию (роутинг)
