### ISSUE TITLE
Создать основу класса Api

### ISSUE THREAD

**Issue by WIVSW** [hikkah-squad/chitchat#22]
# Проблема
Необходимо архитектурное решение для коммуникации клиентского приложения с бэкендом.

# Ожидаемый результат
1. Появится файл `src/api/api.js`, в котором класс `Api`, который является потомком `EventEmitter`.
2. В конструктор этого класса должны быть внедрены зависимости (передаем в контруктор объект-литерал с зависимостями и все его значения сохраняем в приватные переменные):
    - connection
    - liveConnection
3. Появится файл `src/dic.js`, (Dependency Injection Container) пока что это пустой класс, но именно там мы будем инициализировать все наши зависимости.

**Comment by WIVSW** [comment]
Мда... надо что-то сделать с разрешениями

**Comment by Ba-stian** [comment]
Сурен, не туда ткнул
